/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as safuSol from "./Safu.sol";
export type { safuSol };
export type { EasySendCryptoUpgradeable } from "./EasySendCryptoUpgradeable";
