[profile.default]
src = 'contracts'
out = 'artifacts'
auto_detect_solc = false
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat/=node_modules/hardhat/',
]