/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as safuSol from "./Safu.sol";
export { EasySendCryptoUpgradeable__factory } from "./EasySendCryptoUpgradeable__factory";
