/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export { EasySendCrypto__factory } from "./EasySendCrypto__factory";
export { Safu__factory } from "./Safu__factory";
